# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl: 
url: https://li-boxuan.github.io
date_format: "ordinal"
title: Boxuan Li's Blog
author: Boxuan Li

# ---------------- #
#   RSS / Email    #
# ---------------- #
subscribe_rss: /feed.xml
email:

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
paginate: 9
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment
comments_provider: gitment
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: boxuanli
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: li-boxuan
    repo: li-boxuan.github.io
    oauth:
        client_id: c3bcf4567be35a3978be
        client_secret: 5d3e4896271c57a721e6b9ad23cef47adb462586
lazy_load_disqus : false
